//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealershipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int VehicleID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> SaleAmt { get; set; }
        public Nullable<decimal> SaleCommission { get; set; }
        public int ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
