//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealershipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int VehicleID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Miles { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> AcquiredDate { get; set; }
        public Nullable<decimal> AcquiredAmt { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> SaleAmt { get; set; }
        public string VehicleType { get; set; }
    
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
